name: CI

on: [push, pull_request]

env:
  GO11MODULE: on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.7'

    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true

    # NOTE: for some reason this isn't pulling the right version of
    # golanglint-ci. There are a few bugs which have been filed around this
    # which may be related.
    #
    #- name: Run golangci-lint
    #  uses: actions-contrib/golangci-lint@v1
    #  env:
    #    GOROOT: ''
    #  with:
    #    golangci_lint_version: 'v1.27.0'

    - name: Download deps
      run: go mod download

    - name: Run tests
      run: go test -race -v ./...

    - name: Submit coverage report
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go test -covermode=count -coverprofile=profile.cov
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github

